<a href="https://colab.research.google.com/github/Airaat/ml-study/blob/main/pytorch_methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Лабораторная работа №1 "Работа с тензорами Pytorch"**



В данном ноутбуке рассматриваются следующие операции над тензорами в библиотеке PyTorch
1. torch.cat()
2. torch.chunk()
3. torch.index_select()
4. torch.masked_select()
5. torch.narrow()
6. torch.nonzero()
7. torch.reshape()
8. torch.split()
9. torch.t()
10. torch.take()

## torch.cat
---

> `torch.cat(Tuple of Tensors tensors, Int dim=0, *, Tensor out=None) → Tensor`

Объединяет заданную последовательность тензоров `tensors` в заданном измерении `dim`. Все тензоры должны иметь одинаковую форму (за исключением измерения конкатенации) или быть одномерным пустым тензором с размером (0,).




In [ ]:
import torch

a = torch.tensor( [ [1, 2, 3], [4, 5, 6] ] )
b = torch.tensor( [ [7, 9, 1], [2, 3, 5] ] )
t0 = torch.cat((a, b), 0)
t1 = torch.cat((a, b), 1)

print(f"Tensor t0: {t0}\nTensor t1: {t1}")

Tensor t0: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 9, 1],
        [2, 3, 5]])
Tensor t1: tensor([[1, 2, 3, 7, 9, 1],
        [4, 5, 6, 2, 3, 5]])


## **torch.chunk**
---
> `torch.chunk(Tensor input, Int chunks, Int dim=0) → List of Tensors`

Пытается разбить тензор на указанное количество фрагментов. Каждый фрагмент является представлением входного тензора.

> **Примечание:**
функция может возвращать меньше указанного количества фрагментов!

Если размер тензора по заданному измерению `dim` делится на фрагменты `chunks`, все возвращаемые фрагменты будут одинакового размера. Если размер тензора по заданному измерению `dim` не делится на фрагменты, все возвращаемые фрагменты будут одинакового размера, за исключением последнего. Если такое деление невозможно, эта функция может возвращать меньше указанного количества фрагментов.

In [ ]:
chunked = torch.arange(12).chunk(3)
chunked

(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10, 11]))

## **torch.index_select**
---
> `torch.index_select(Tensor input, Int dim, IntTensor|LongTensor index, *, Tensor out=None) → Tensor`

Возвращает новый тензор, который индексирует входной тензор `input` по размерности `dim`, используя записи в `index` типа **LongTensor**.

Возвращенный тензор имеет то же количество измерений, что и исходный тензор `input`. Размерность `dim` имеет тот же размер, что и длина `index`; другие измерения имеют тот же размер, что и в исходном тензоре.

> **Примечание:** Возвращенный тензор **не использует** то же хранилище, что и исходный тензор. Если `out` имеет форму, отличную от ожидаемой, мы неявно изменяем его на правильную форму, перераспределяя базовое хранилище, если необходимо.

In [ ]:
x = torch.randn(3, 4)

indices = torch.tensor([0,2])
t0 = torch.index_select(x, 0, indices)
t1 = torch.index_select(x, 1, indices)

print(f"Original x: {x}\nTensor t0: {t0} \nTensor t1: {t1}")

Original x: tensor([[ 0.0519,  1.1715,  0.6080,  0.1381],
        [ 0.0767,  1.4485, -0.8839, -0.7886],
        [-0.8584,  0.5195,  0.1791,  0.8493]])
Tensor t0: tensor([[ 0.0519,  1.1715,  0.6080,  0.1381],
        [-0.8584,  0.5195,  0.1791,  0.8493]]) 
Tensor t1: tensor([[ 0.0519,  0.6080],
        [ 0.0767, -0.8839],
        [-0.8584,  0.1791]])


## **torch.masked_select**
---
> `torch.masked_select(Tensor input, BoolTensor mask, *, Tensor out=None) → Tensor`

Возвращает новый одномерный тензор, который индексирует входной тензор `input` в соответствии с булевой маской `mask` типа **BoolTensor**.

Формы тензора `mask` и входного тензора `input` не обязательно должны совпадать, но они должны быть транслируемыми.

In [ ]:
x = torch.randn(3, 4)

mask = x.ge(0.5) # Элементы >= 0.5
masked = torch.masked_select(x, mask)

print(f"Original: {x}\nMask: {mask} \nNew tensor: {masked}")

Original: tensor([[-0.1109,  0.4837, -0.2886,  0.3495],
        [ 2.5799,  0.8670,  0.9530, -1.0203],
        [-0.7763,  1.5512, -1.3109,  0.4612]])
Mask: tensor([[False, False, False, False],
        [ True,  True,  True, False],
        [False,  True, False, False]]) 
New tensor: tensor([2.5799, 0.8670, 0.9530, 1.5512])


## **torch.narrow**
---
> `torch.narrow(Tensor input, Int dim, Int|Tensor start, Int length) → Tensor`

Возвращает новый тензор, который является суженной версией входного тензора `input`. Размерность `dim` — это вход от `start` до `start` + `length`. Возвращаемый тензор и входной тензор `input` совместно используют одно и то же базовое хранилище.



In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t0 = torch.narrow(x, 0, 0, 2)
t1 = torch.narrow(x, 1, 1, 2)
t2 = torch.narrow(x, -1, torch.tensor(-1), 1)

t1

tensor([[2, 3],
        [5, 6],
        [8, 9]])

## **torch.nonzero**
---
> ` torch.nonzero(Tensor input, *, out=None, Bool as_tuple=False) → LongTensor or tuple of LongTensors
`

Когда `as_tuple=False` (по умолчанию):

Возвращает тензор, содержащий индексы всех ненулевых элементов `input`. Каждая строка в результате содержит индексы ненулевого элемента `input`. Результат сортируется лексикографически, причем последний индекс изменяется быстрее всего (C-style).

Если `input` имеет *n* измерений, то результирующий тензор индексов `out` имеет размер *(z×n)(z×n)*, где *z* — общее количество ненулевых элементов во входном тензоре `input`.

Когда `as_tuple=True`:

Возвращает кортеж одномерных тензоров, по одному для каждого измерения в `input`, каждый из которых содержит индексы (в этом измерении) всех ненулевых элементов `input`.

Если `input` имеет *n* измерений, то результирующий кортеж содержит *n* тензоров размером *z*, где *z* — общее количество ненулевых элементов во входном тензоре.

В качестве особого случая, когда `input` имеет нулевое измерение и ненулевое скалярное значение, они рассматриваются как одномерный тензор с одним элементом.

In [ ]:
torch.nonzero(torch.tensor([1, 1, 1, 0, 1]))

tensor([[0],
        [1],
        [2],
        [4]])

In [ ]:
torch.nonzero(torch.tensor([[0.6, 0.0, 0.0, 0.0],
                            [0.0, 0.4, 0.0, 0.0],
                            [0.0, 0.0, 1.2, 0.0],
                            [0.0, 0.0, 0.0,-0.4]]))


tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]])

In [ ]:
 torch.nonzero(torch.tensor([1, 1, 1, 0, 1]), as_tuple=True)

(tensor([0, 1, 2, 4]),)

In [ ]:
torch.nonzero(torch.tensor([[0.6, 0.0, 0.0, 0.0],
                            [0.0, 0.4, 0.0, 0.0],
                            [0.0, 0.0, 1.2, 0.0],
                            [0.0, 0.0, 0.0,-0.4]]), as_tuple=True)

(tensor([0, 1, 2, 3]), tensor([0, 1, 2, 3]))

In [ ]:
torch.nonzero(torch.tensor(5), as_tuple=True)

(tensor([0]),)

## **tensor.reshape**
---
> `torch.reshape(Tensor input, Tuple of Int shape) → Tensor`

Возвращает тензор с теми же данными и количеством элементов, что `input`, но с указанной формой.

Одно измерение может быть -1, и в этом случае оно выводится из оставшихся измерений и количества элементов в `input`.

In [ ]:
a = torch.arange(4.)
torch.reshape(a, (2, 2))

In [ ]:
b = torch.tensor([[0, 1], [2, 3]])
torch.reshape(b, (-1,))

tensor([0, 1, 2, 3])

## **torch.split**
---
> `torch.split(Tensor tensor, Int|List of Int split_size_or_sections, Int dim=0) -> Tuple of Tensors
`

Разбивает тензор на части. Каждая часть является представлением исходного тензора.

Если `split_size_or_sections` — целочисленный тип, то тензор будет разбит на части одинакового размера (если это возможно). Последняя часть будет меньше, если размер тензора по заданному измерению `dim` не делится на `split_size`.

Если `split_size_or_sections` — список, то тензор будет разбит на длину списка с размерами в `dim` в соответствии с его элеметами

In [ ]:
a = torch.arange(10).reshape(5, 2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
torch.split(a, 2)

(tensor([[1, 2, 3],
         [4, 5, 6]]),)

In [ ]:
torch.split(a, [1, 4])

(tensor([[0, 1]]),
 tensor([[2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))

## **torch.t**
---
> `torch.t(Tensor input) -> Tensor`

Ожидается что `input` будет двумерным тензором и транспонирует матрицу.

Скалярной значение и вектор останутся без изменений

In [ ]:
# Скалярное значение
x = torch.randn(())
x, torch.t(x)

(tensor(0.2719), tensor(0.2719))

In [ ]:
# Одномерный вектор
x = torch.randn(3)
x, torch.t(x)

(tensor([0.2025, 0.2695, 0.8593]), tensor([0.2025, 0.2695, 0.8593]))

In [ ]:
# Матрица
x = torch.randn(2, 3)
x, torch.t(x)

(tensor([[ 1.4445,  0.5063,  0.9367],
         [ 0.1302,  0.3908, -0.1303]]),
 tensor([[ 1.4445,  0.1302],
         [ 0.5063,  0.3908],
         [ 0.9367, -0.1303]]))

## **torch.take**
---
> `torch.take(Tensor input, LongTensor index) → Tensor`

Возвращает новый тензор с элементами `input` по заданным индексам. Входной тензор обрабатывается так, как если бы он рассматривался как одномерный тензор. Результат принимает ту же форму, что и индексы.

In [ ]:
src = torch.tensor([[4, 3, 5],
                    [6, 7, 8]])
torch.take(src, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])